services:
  vsc-server-setup-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    init: true
    volumes:
      - ./:/workspace
      - ~/.ssh:/root/.ssh:ro
      
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

      - /var/run/docker.sock:/var/run/docker.sock:ro