services:
  vsc-server-setup-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: vsc-server-setup-dev
    volumes:
      - ./:/workspace
      - ~/.ssh:/root/.ssh:ro
      
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro